### ISSUE TITLE
Top Language computation

### ISSUE THREAD

**Issue by lukezirngibl** [remotion-dev/github-unwrapped#166]
We may need to take a second look at the top language computation

``` baseData.contributionsCollection.commitContributionsByRepository.forEach(
    (i) => {
      i.repository.languages.edges
        .filter((e) => !NOT_LANGUAGES_OBJ[e.node.name.toLocaleLowerCase()])
        .forEach((l) => {
          acc[l.node.name] = {
            color: l.node.color,
            value: l.size + (acc[l.node.name]?.value || 0),
          };
        });
    },
  );

  const topLanguages = Object.entries(acc)
    .sort((a, b) => b[1].value - a[1].value)
    .map((i) => ({
      languageName: i[0],
      color: i[1].color,
    }))
    .slice(0, 3);
    ```

**Comment by mandar1jn** [comment]
If this helps to debug: kotlin is reported as my 2nd most used language. I have written 3 lines of Java this year. No kotlin

**Comment by luckasRanarison** [comment]
By the way, forked repos are also counted in the top languages, it makes the top languages ranking really inaccurate.

**Comment by LinqLover** [comment]
Same here. It reports C, C++, Jupyter as my top languages. Vast majority of my commits were in Smalltalk and Python though.

**Comment by ramadanomar** [comment]
I think an approach similar to the [github-readme-stats card project](https://github.com/anuraghazra/github-readme-stats#top-languages-card) would be best. Really want to share the video but the top language is too inaccurate

**Comment by JonnyBurger** [comment]
Forked repos are now excluded: 3e3c1620cab10e9fd07a6d550f712139206c9737

**Comment by LinqLover** [comment]
Great, is this already live? It still shows the old languages for me.

**Comment by JonnyBurger** [comment]
@LinqLover Yes, but to reset the stats, you need to login with GitHub again! Does this work?

**Comment by ramadanomar** [comment]
Does this also include commits made inside an org repo? I granted the app perms to the org. Still seems really off

**Comment by luckasRanarison** [comment]
It still doesn't work.

> 3e3c1620cab10e9fd07a6d550f712139206c9737

I don't see how is this affecting languages stats from forked repo, doesn't this just remove commits? Shouldn't the languages be filtered by checking if the repo is a fork in  `baseQuery`?

https://github.com/remotion-dev/github-unwrapped-2023/blob/main/src/server/queries/base.query.ts#L48-L48

**Comment by LinqLover** [comment]
> @LinqLover Yes, but to reset the stats, you need to login with GitHub again! Does this work?

I think it doesn't :)

**Comment by JonnyBurger** [comment]
You all were right! The top language computation is now much more reasonable.
Indeed, the algorithm wasn't as described in the FAQ.

The first section here explains how you can un-cache your video and get a proper one: https://githubunwrapped.com/about
