### ISSUE TITLE
Video Download Bug

### ISSUE THREAD

**Issue by oppatrickk** [remotion-dev/github-unwrapped#171]
I have given private access to my repos

When downloading the video, it downloads the video without the private metrics.

**Comment by biplobsd** [comment]
Same. Is there any extension downloader?

**Comment by patsalv** [comment]
@oppatrickk @biplobsd Until now, the videos got only re-rendered with the new stats if you logged in via the /about page. This just got fixed with #172. 
Also, make sure to  enable "Private contributions" in your GitHub profile.
