### ISSUE TITLE
The username goes off-screen if it's too long

### ISSUE THREAD

**Issue by warningnonpotablewater** [remotion-dev/github-unwrapped#181]
My username is "warningnonpotablewater", which causes it to go off-screen during the "This is my" section due to being too long.

https://githubunwrapped.com/warningnonpotablewater

![titled](https://github.com/remotion-dev/github-unwrapped-2023/assets/17949857/1106ad58-f458-4e9d-94ed-bb0577a913dc)

**Comment by JonnyBurger** [comment]
Thanks for letting us know! We'll redeploy the rendering soon. Here is how you will be able to re-trigger a render: 

https://githubunwrapped.com/about
