### ISSUE TITLE
Top Language

### ISSUE THREAD

**Issue by nico-martin** [remotion-dev/github-unwrapped#183]
![Screenshot_20231213-151941~2](https://github.com/remotion-dev/github-unwrapped-2023/assets/8424136/20a2f9ed-61a2-4c84-a10d-436c54f5f471)
My No. 1 Language is Java but I dont think I wrote a single line of Java in the last years. Is it possible to see where unwrapped gets the information from?

**Comment by AmoDinho** [comment]
same story for me, it told me my #1 is Python but have not reviewed or wrote any Python that I've committed to Github.

**Comment by akkshayTandon** [comment]
Yes , it's showing my no. 1 language as typescript but i never wrote typescript.

**Comment by cassidoo** [comment]
Same, I also never wrote TypeScript this year but it's my #1 as well!

**Comment by nico-martin** [comment]
I set up the project locally and there it seems to work. So it might already be fixed.
But there also is a MongoDB that caches the github stats. @JonnyBurger, is it possible to reload the data from Github?

**Comment by nico-martin** [comment]
Oooooh.. and I don't actually agree to this one :)
https://github.com/remotion-dev/github-unwrapped-2023/blob/main/src/server/get-stats-from-github.ts#L13

![image](https://github.com/remotion-dev/github-unwrapped-2023/assets/8424136/b2892ce7-1dcb-4086-bc16-bdc06941019d)

**Comment by JonnyBurger** [comment]
Ok, @nico-martin I think in 2023 we can let CSS pass as a programming language.. b7700c8941be976cc25f5d6244bb779e363b810c

I'll sample some of your public profiles and see why you are getting the wrong language!

**Comment by nico-martin** [comment]
The strang thing is that when I set up the project locally and run the `executeGitHubGraphQlQuery` I^, getting the correct languages (JS/PHP/TS). But when I render the video on https://githubunwrapped.com/, I get (PHP/TS/JAVA)

**Comment by JonnyBurger** [comment]
You all were right! The top language computation is now much more reasonable.

The first section here explains how you can un-cache your video and get a proper one: https://githubunwrapped.com/about

**Comment by nico-martin** [comment]
@JonnyBurger, perfect! Now it works for me :)!
