### ISSUE TITLE
"My most productive time" wrong value

### ISSUE THREAD

**Issue by dottxado** [remotion-dev/github-unwrapped#185]
The unwrap reports a wrong "my most productive time" value: in my case, it is 5PM and it's completely wrong because at that time I'm not in front of my computer (or smartphone).
Maybe can be a timezone issue?

**Comment by JonnyBurger** [comment]
You are right!

There was a bug where data from previous years was included.
Deleting those gives this now:

![image](https://github.com/remotion-dev/github-unwrapped-2023/assets/1629785/19cf1946-dd51-4099-84aa-30530f3d524a)

Pushing this, you can learn how to generate another video here: githubunwrapped.com/about

Your timezone is set to UTC+2. If that is wrong, then the data could also turn out wrong.
