### ISSUE TITLE
shell script not considered a language?

### ISSUE THREAD

**Issue by cgsdev0** [remotion-dev/github-unwrapped#194]
https://github.com/remotion-dev/github-unwrapped-2023/blob/9ede2dbc3d9c9629944c9762c3089ccade7ad19e/src/server/get-stats-from-github.ts#L13-L20

😢 

guess i didn't do any programming this year

my unwrapped just completely ignored my most successful repo

**Comment by JonnyBurger** [comment]
Ok, convinced! 😝 

06bff47258b65d88c21bb723d93fd0b29d16bf92

How to reset: https://githubunwrapped.com/about
