### ISSUE TITLE
Download button is not downloading the updated video

### ISSUE THREAD

**Issue by umair313** [remotion-dev/github-unwrapped#196]
I created the video download it and then included private data, after creating the video I can see the changes in it but download button is still downloading the old video.

**Comment by wariosolis** [comment]
@umair313 Check this https://github.com/remotion-dev/github-unwrapped-2023/issues/171#issuecomment-1853550027

#171

**Comment by JonnyBurger** [comment]
We fixed the reset bug now! How to reset: https://githubunwrapped.com/about
