### ISSUE TITLE
Reset cache for user

### ISSUE THREAD

**Issue by wolflu05** [remotion-dev/github-unwrapped#197]
Hello, GitHub-unwrapped is a really cool idea, I already tried it a few weeks ago, but today I tried to regenerate the statistics since I made a few commits in the past. Is there any way to clear the cache for a user and generate the statistics from scratch so that recent contributions are included? About last year, I found this comment: https://github.com/remotion-dev/github-unwrapped-2022/issues/26#issuecomment-1365772068 so I'm curious if this has made it in this years unwrapped tool, or if you could manually reset my stats?

**Comment by JonnyBurger** [comment]
Yes! See here how you can reset your video: https://githubunwrapped.com/about

**Comment by wolflu05** [comment]
Thanks for the quick answer @JonnyBurger , didn't see this before and it took me a long time to find it on that page. But unfortunately this does not work for me. I used the one with the `?reset=true` query parameter, but the page loads instantly and the old data is still used.

**Comment by JonnyBurger** [comment]
@wolflu05 You are right! Just deployed a fix!

**Comment by wolflu05** [comment]
Thank you for the fix, it worked now. 👍
