### ISSUE TITLE
[Question] Lambda invocations count clarification needed.

### ISSUE THREAD

**Issue by RukshanJS** [remotion-dev/github-unwrapped#198]
- I just did a simple execution of the code, with just one aws region (for testing). I have the quota for concurrency at default 10 (already requested an increase but that's not the point). I get `Rate Exceeded.` error in network tab.
- When I go to aws console, i see a lot of concurrent runs for the function. 

Can someone please explain what a concurrent run is in relation with a single video render? Do we expect to see *just one invocation per video render*?

**Comment by RukshanJS** [comment]
By further studying, i got to know that multiple lambda functions are created to render the video part-wise, which makes sense from a render-performance perspective. https://www.remotion.dev/docs/lambda#how-it-works

But is there any way that i can configure the number of max lambda functions created (so that I can stay within the max concurrent lambda limit)?

**Comment by JonnyBurger** [comment]
Answered in https://github.com/remotion-dev/remotion/issues/3305
