### ISSUE TITLE
Video is not showing latest data such as commit and repo stars

### ISSUE THREAD

**Issue by htutwaiphyoe** [remotion-dev/github-unwrapped#199]
I created my #githubunwrapped video a few weeks ago. Then when I create it again later, it does not show my latest commit count and other data. 
You can visit my account: https://githubunwrapped.com/htutwaiphyoe
Commits are showing untill 13 Dec.

**Comment by JonnyBurger** [comment]
You can reset the video like this: https://githubunwrapped.com/about this mechanic has just been fixed!
