### ISSUE TITLE
failing to generate video, download unavailable

### ISSUE THREAD

**Issue by peclarke** [remotion-dev/github-unwrapped#203]
The following errors occurred after clicking play to generate the video. The video begins to generate and then concludes with download unavailable. 

Two different types of internet connections were tried and both brought the same error.
No requests were failing. The final request that went through was a blob retrieval for python, which was successful.

The following errors appeared in the console.log:
![Screen Shot 2024-01-25 at 11 15 41 am](https://github.com/remotion-dev/github-unwrapped-2023/assets/30831649/acd6090d-6220-4465-aa14-aad71a8b3259)

![Screen Shot 2024-01-25 at 11 16 13 am](https://github.com/remotion-dev/github-unwrapped-2023/assets/30831649/478312f5-dcb5-4a63-8de8-081fc8beaaab)

**Comment by JonnyBurger** [comment]
Thanks for reporting! Deployed a fix now.

How to reset: https://githubunwrapped.com/about
