### ISSUE TITLE
I can not download!

### ISSUE THREAD

**Issue by Rasulwebs** [remotion-dev/github-unwrapped#204]
I can't download the video generated for my GitHub profile via https://githubunwrapped.com/.

Download button
The text "Download unavailable" is written
![Screenshot 2024-01-25 162625](https://github.com/remotion-dev/github-unwrapped-2023/assets/109275421/86676f03-4b80-4e9b-b051-28d8d1a21c59)

**Comment by uwussimo** [comment]
the same issue here

**Comment by JonnyBurger** [comment]
Thanks, I deployed a fix now! How to reset:

https://githubunwrapped.com/about
