### ISSUE TITLE
Guys no github unwrapped 2024?

### ISSUE THREAD

**Issue by AswinPKumar01** [remotion-dev/github-unwrapped#206]

**Comment by priyansh2313** [comment]
Lets try shall we!!

**Comment by JonnyBurger** [comment]
There will be no new campaign for 2024, we are all a bit busy with other projects this year 😔

However, I will update this repo to make it ready for 2024.

**Comment by Mattral** [comment]
Thank you for update

**Comment by AswinPKumar01** [comment]
Oh! Okay thanks for letting us know!
