### ISSUE TITLE
2024 version

### ISSUE THREAD

**Issue by justinfernald** [remotion-dev/github-unwrapped#209]
Will there be a 2024 version of this?

**Comment by prakhar1144** [comment]
See: https://github.com/remotion-dev/github-unwrapped-2022/issues/38#issuecomment-2505632309

**Comment by ozturksirin** [comment]
+1

**Comment by jis3r** [comment]
+1

**Comment by euotiniel** [comment]
+1

**Comment by sendhyrama** [comment]
=3

**Comment by aldotobing** [comment]
+1

**Comment by hoc081098** [comment]
:rocket:

**Comment by ragnarok22** [comment]
This is the PR #210

**Comment by justinfernald** [comment]
> This is the PR [#210](https://github.com/remotion-dev/github-unwrapped/pull/210)

It is crazy it hasn't been merged in yet.

**Comment by justinfernald** [comment]
> > This is the PR [#210](https://github.com/remotion-dev/github-unwrapped/pull/210)
> 
> It is crazy it hasn't been merged in yet.

But we will remain patient lol

**Comment by amjeed-ay** [comment]
we are waiting for 2024 ?

**Comment by ragnarok22** [comment]
Let's be patient. It isn't just change 2023 to 2024. I saw he is also fixing other stuff.

**Comment by JonnyBurger** [comment]
Planning to ship this later today!

**Comment by JonnyBurger** [comment]
It's now live! Enjoy https://githubunwrapped.com
