### ISSUE TITLE
Video player - themes button

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped#24]
This might not be implemented at all, but just in case we have time and think about doing this as well.
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/374e21d0-8703-497a-9eda-a123afc82aed)

**Comment by MehmetAdemi** [comment]
@JonnyBurger, are there going to be themes this year?

I'm asking bc. of @maria-paul's note here: https://github.com/remotion-dev/github-unwrapped-2023/issues/43#issuecomment-1838828875

**Comment by JonnyBurger** [comment]
Yes, there will be themes (rocket switcher)

**Comment by MehmetAdemi** [comment]
Alright, so I leave this task open since it seems after all we are going for themes this year too. 🙌

**Comment by MehmetAdemi** [comment]
@JonnyBurger can we make these themes a little more visible? I don't think it's enough obvious to click on the spaceship image to change the theme.

**Comment by JonnyBurger** [comment]
Not going to do it realistically
