### ISSUE TITLE
Pomotional assets - design some banners and cards

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/github-unwrapped#31]
We need some assets to promote the event before, during and maybe after the campaign.

Assets to be posted and used by Remotion
- [x] 3 days before - "it's coming 👀"
- [x] tomorrow - "reminder"
- [x] release day - "take off 🚀"
- [ ] mid-campaign - "create your video"
- [ ] post-campaign - "thanks for participating, create your own campaign" (pointing out to the source code)

Assets to be posted and used by GitHub
- [x] release day - "take off 🚀"
- [x] mid-campaign - "create your video"

Formats we need:
- square (1080 x 1080px) - X/Twitter, Linkedin, Instagram, and YouTube Community
- wide (1920 x 1080px) - Discord Server, Newsletter, YouTube Thumbnail (behind the scene video), Remotion Showcase section
- wide (1200 x 630px) - [README](https://github.com/remotion-dev/github-unwrapped-2022/blob/main/README.md), [Product Hunt Launch](https://www.producthunt.com/products/github-unwrapped-2022#github-unwrapped-2022), og:image (see: #46)

Example from GitHub Unwrapped 2022:
- "tomorrow" posted by Remotion: https://twitter.com/Remotion/status/1604575946664824832
- "post-campaign" - posted by Remotion: https://twitter.com/Remotion/status/1605957413353312256

- "release day" posted by GitHub: https://twitter.com/github/status/1604867535203074048

**Comment by MehmetAdemi** [comment]
@JonnyBurger, you created a new task/issue for the README (#48). For all the other assets that we need, can you refer to this task/issue and involve the designers? You might want to edit the thread head.

**Comment by maria-paul** [comment]
So updates on this issue:

**3 days before:**
Still image 1080x1080px (ready)

**1 day before:**
Still image 1080x1080px (ready)

**Launch day:**
Video 1080x1080px, can be adjusted in any format (storyboard ready, Jonny needs to animate it)

**Mid-campaign:**
Not discussed yet, not urgent.

**Post-campaign:**
I guess we use a still image we already have. (ready)

----
Also I have prepared the assets mentioned in #109 and #112. 

Everything mentioned above is on Figma:)

**Comment by MehmetAdemi** [comment]
@maria-paul, just great! 
Thank you so much for giving all those assets a nice order. It's easy to find what I need this way!

**Comment by MehmetAdemi** [comment]
@JonnyBurger, is there a launch day video in development?

Asking because of this:
![Image](https://github.com/remotion-dev/github-unwrapped-2023/assets/86873911/b22bf07f-7242-41d2-89a5-2d657f3b896e)

**Comment by JonnyBurger** [comment]
Not yet 😅
But I'll start today hopefully
